#!/usr/bin/env bash
set -euo pipefail
source ./common.sh

key_vault_name="$1"
datadog_api_key="datadog-api-key"

az login --identity
dd_api_key="$(az keyvault secret show --vault-name $key_vault_name --name $datadog_api_key --query "value" -o tsv | jq -r '.[0].api_key')"

# Fetch the static hostname
static_hostname=$(hostnamectl --static)
if [[ -z "$static_hostname" ]]; then
  echo "Error: Unable to fetch the static hostname/computer name."
  exit 1
fi

# Construct the opt_cluster variable
opt_cluster="ing_az_${static_hostname}"

# ===================== CONFIG (via env vars or extension settings) =====================
DD_API_KEY="${dd_api_key}"
DD_SITE="datadoghq.eu"
DD_LOG_PATH="/data/adcdata/logs/pricing/incr_poller.log,/data/adcdata/logs/pricing/incr_ingester.log,/data/adcdata/logs/eanpoller.log,/data/adcdata/logs/eaningester.log,/data/adcdata/logs/fxpoller.log,/data/adcdata/logs/fxingester.log"
DD_SERVICE_NAME="adc_ingestion"
PROJECT_NAME="adc_ingestion"

# Paths
DD_AGENT_ETC="/etc/datadog-agent"
DD_AGENT_CONF="${DD_AGENT_ETC}/datadog.yaml"
DD_CONF_DIR="${DD_AGENT_ETC}/conf.d"
DD_CUSTOM_DIR="${DD_CONF_DIR}/customlog.d"
DD_CUSTOM_CONF="${DD_CUSTOM_DIR}/conf.yaml"

# ===================== Source mapping function =====================
get_dd_source() {
  case "$1" in
    "/data/adcdata/logs/pricing/incr_poller.log")   echo "pricing_poller" ;;
    "/data/adcdata/logs/pricing/incr_ingester.log") echo "pricing_ingester" ;;
    "/data/adcdata/logs/eanpoller.log")             echo "ean_poller" ;;
    "/data/adcdata/logs/eaningester.log")           echo "ean_ingester" ;;
    "/data/adcdata/logs/fxpoller.log")              echo "fx_poller" ;;
    "/data/adcdata/logs/fxingester.log")            echo "fx_ingester" ;;
    *)                                              echo "unknown_source" ;;
  esac
}

# ===================== 1) Verify agent exists =====================
ts "Checking for datadog-agent service (must already be installed)…"
if ! systemctl status datadog-agent >/dev/null 2>&1; then
  err "datadog-agent service not found. Install the agent first, then re-run this script."
  exit 1
fi
ok "datadog-agent service is present."

# ===================== 2) Write datadog.yaml =====================
ts "Writing ${DD_AGENT_CONF}…"
mkdir -p "${DD_AGENT_ETC}"
cat <<EOF | tee "${DD_AGENT_CONF}" > /dev/null
## Generated by startup_datadog.sh
api_key: ${DD_API_KEY}
site: ${DD_SITE}
skip_ssl_validation: true
process_config:
  enabled: true
apm_config:
  enabled: true
  apm_non_local_traffic: true
logs_enabled: true
tags:
    - opt-componentname:${PROJECT_NAME}
    - opt-cluster:${opt_cluster}
EOF
chmod 640 "${DD_AGENT_CONF}"
chown dd-agent:dd-agent "${DD_AGENT_CONF}"
ok "Wrote ${DD_AGENT_CONF}"

ts "Verifying the contents of ${DD_AGENT_CONF}"
if [ -f "${DD_AGENT_CONF}" ]; then
  ok "${DD_AGENT_CONF} exists and is not empty."
else
  err "Expected ${DD_AGENT_CONF} not found!"
fi

# ===================== 3) Create custom log integration =====================
ts "Configuring custom logs at ${DD_CUSTOM_CONF}"
mkdir -p "${DD_CUSTOM_DIR}"
cat <<EOF | tee "${DD_CUSTOM_CONF}" > /dev/null
# Generated by datadog_ingestion.sh
logs:
EOF

IFS=',' read -r -a _paths <<< "${DD_LOG_PATH}"
for log_path in "${_paths[@]}"; do
  DD_SOURCE="$(get_dd_source "$log_path")"

  cat <<EOL | tee -a "${DD_CUSTOM_CONF}" >/dev/null
  - type: file
    path: "${log_path}"
    service: "${DD_SERVICE_NAME}"
    source: "${DD_SOURCE}"
    sourcecategory: sourcecode 
EOL
done
chmod 644 "${DD_CUSTOM_CONF}"
chown dd-agent:dd-agent "${DD_CUSTOM_CONF}"
ok "Wrote ${DD_CUSTOM_CONF}"

# ===================== 4) Validate files =====================
ts "Validating generated files…"
for f in "${DD_AGENT_CONF}" "${DD_CUSTOM_CONF}"; do
  [ -f "$f" ] && ok "Found: $f" || { err "Missing: $f"; exit 1; }
done

# ===================== 5) Verify the changes =====================
ts "Verifying the contents of ${DD_CUSTOM_CONF}"
if [ -f "${DD_CUSTOM_CONF}" ]; then
  cat "${DD_CUSTOM_CONF}"
else
  err "Expected ${DD_CUSTOM_CONF} not found!"
fi

# ===================== 6) Permission fixes  & Restart the agent =====================
chown -R ingres:ingres /data/adcdata/logs
chmod -R 770 /data/adcdata/logs
usermod -aG ingres dd-agent
if ! systemctl is-active --quiet datadog-agent; then
  echo "datadog-agent is not active. Starting the service..."
  systemctl start datadog-agent
  echo "datadog-agent service started."
else
  echo "datadog-agent is already active."
fi
ts "Restarting datadog-agent"
systemctl restart datadog-agent
ok "datadog-agent restarted successfully"

echo "datadog_ingestionVM.sh executed successfully."