#
# Trigger jobs for IaC pipelines
#
# Notes:
# 1 - pipelines are included so may be local or BAS-BC3 stock versions
# 2 - pipelines should be pinned using a versioned tag reference. This is especially important when using BAS-BC3 stock pipelines.
# 3 - include spec variables are only used for labeling stages - they do not control pipeline behaviour. So they can be shortened for readability.
# 4 - include spec variables cannot be set with CICD default, pipeline, or job variables - this is a limitation of GITLAB
#
include:
  - "/environments/ppr/pipeline-vars/pipeline-vars.yaml"
  - "/environments/ppr/subscription-vars/subscription.yaml"

stages:
  - ppr

## IaC template - used by all jobs
.iac_ppr_deploy_template:
  stage: ppr
  extends: [.ppr_pipeline_vars, .ppr_subscription_vars_cus]
  variables:
    REGION: "cus"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    BAS_ENABLE_DYNAMIC_OPE: "true"
    BAS_ENABLE_DESTROY: "false"
    BAS_ENABLE_DEBUG: "false"
  when: manual

###################
### Subnet  #######
###################
deploy-ppr-nonrtbl-network-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_nonrtbl_network_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/nonrtbl-network"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/cus/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "nonrtbl_network"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

###################
### Key Vault  ####
###################
deploy-ppr-key-vault-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_key_vault_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/key_vault"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/cus/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "key-vault"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true



######################
### Windows Webapp ###
######################
deploy-ppr-windows_webapp-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_windows_webapp_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/windowswebapp"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/cus/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "windows-webapp"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

######################
### Linux Webapp ###
######################
deploy-ppr-linux_webapp-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_linux_webapp_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/linuxwebapp"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/cus/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "linux-webapp"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

######################
### Windows VM #######
######################
deploy-ppr-windows-vm-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_windowsvm_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/windowsvm"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/cus/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "windows-vm"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

####################
### Linux VM #######
####################
deploy-ppr-linux-vm-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_linuxvm_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/linuxvm"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/cus/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "linux-vm"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

############################
### Application Gateway ####
############################
deploy-ppr-application-gateway-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_application_gateway_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/application_gateway"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${REGION}/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
    BAS_VS_SECRET_LIST: |
      TF_VAR_cert_password@gitlab/app-52161/kv/cert/ppr@cert_password
      TF_VAR_couchdb_cert@gitlab/app-52161/kv/cert/ppr@couchdb_cert
      TF_VAR_guidance_cert@gitlab/app-52161/kv/cert/ppr@guidance_cert
      TF_VAR_collection_cert@gitlab/app-52161/kv/cert/ppr@collection_cert
      TF_VAR_actualsbre_cert@gitlab/app-52161/kv/cert/ppr@actualsbre_cert
      TF_VAR_broker_cert@gitlab/app-52161/kv/cert/ppr@broker_cert
      TF_VAR_brokerxl_cert@gitlab/app-52161/kv/cert/ppr@brokerxl_cert
      TF_VAR_estimatesbre_cert@gitlab/app-52161/kv/cert/ppr@estimatesbre_cert
      TF_VAR_estimatessdi_cert@gitlab/app-52161/kv/cert/ppr@estimatessdi_cert
      TF_VAR_guidancebre_cert@gitlab/app-52161/kv/cert/ppr@guidancebre_cert
      TF_VAR_hvpweb_cert@gitlab/app-52161/kv/cert/ppr@hvpweb_cert
      TF_VAR_qdct_cert@gitlab/app-52161/kv/cert/ppr@qdct_cert
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v4.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "application-gateway"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

##############################
### Azure Compute Gallery ####
##############################
deploy-ppr-azure-compute-galleries-1:
  extends: [.iac_ppr_deploy_template]
  variables:
    CLUSTER: "${ENV}_${REGION}_azure_compute_galleries_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/azure_compute_galleries"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${REGION}/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${REGION}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-production-pipeline-v3.yaml'
        inputs:
          env: "ppr"
          rgn: "cus"
          svc: "azure_compute_galleries"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true