#
# Trigger jobs for IaC pipelines
#
# Notes:
# 1 - pipelines are included so may be local or BAS-BC3 stock versions
# 2 - pipelines should be pinned using a versioned tag reference. This is especially important when using BAS-BC3 stock pipelines.
# 3 - include spec variables are only used for labeling stages - they do not control pipeline behaviour. So they can be shortened for readability.
# 4 - include spec variables cannot be set with CICD default, pipeline, or job variables - this is a limitation of GITLAB
#
include:
  - "/environments/qa/pipeline-vars/pipeline-vars.yaml"
  - "/environments/qa/subscription-vars/subscription.yaml"

stages:
  - qa

## IaC template - used by all jobs
.iac_qa_deploy_template:
  stage: qa
  extends: [.qa_pipeline_vars, .qa_subscription_vars_eus]
  variables:
    REGION: "eus2"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    BAS_ENABLE_DYNAMIC_OPE: "true"
    BAS_ENABLE_DESTROY: "true"
    BAS_ENABLE_DEBUG: "false"
  when: manual

###################
### Subnet  #######
###################
deploy-qa-nonrtbl-network-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_nonrtbl_network_1"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/nonrtbl-network"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.29
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "nonrtbl_network"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

###################
### Key Vault  ####
###################
deploy-qa-key-vault-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_key_vault_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/key_vault"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "key-vault"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

###############
### SQL MI ####
###############
deploy-qa-sqlmi-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_sqlmi_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/azuresqlmi"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -refresh=false"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "sqlmi"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

######################
### Windows Webapp ###
######################
deploy-qa-windows_webapp-1:
  extends: [.iac_qa_deploy_template]
  # needs:
  #   - 1-deploy-qa-eus
  variables:
    CLUSTER: "${ENV}_windows_webapp_1"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/windowswebapp"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.29
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "windows-webapp"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

######################
### Linux Webapp ###
######################
deploy-qa-linux_webapp-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_linux_webapp_1"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/linuxwebapp"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.29
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "linux-webapp"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

####################
### Linux VM #######
####################
deploy-qa-linux-vm-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_linuxvm_1"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/linuxvm"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.29
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "linux-vm"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

######################
### Windows VM #######
######################
deploy-qa-windows-vm-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_windowsvm_1"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/windowsvm"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.29
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "windows-vm"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true



############################
### Application Gateway ####
############################
deploy-qa-application-gateway-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_application_gateway_1"
    MANIFEST_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/manifest.yaml"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/application_gateway"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
    BAS_VS_SECRET_LIST: |
      TF_VAR_cert_password@gitlab/app-52161/kv/cert/qa@cert_password
      TF_VAR_couchdb_cert@gitlab/app-52161/kv/cert/qa@couchdb_cert
      TF_VAR_qdctweb_cert@gitlab/app-52161/kv/cert/qa@qdctweb_cert
      TF_VAR_hvpweb_cert@gitlab/app-52161/kv/cert/qa@hvpweb_cert
      TF_VAR_guidancebre_cert@gitlab/app-52161/kv/cert/qa@guidancebre_cert
      TF_VAR_estimatessdi_cert@gitlab/app-52161/kv/cert/qa@estimatessdi_cert
      TF_VAR_estimatesbre_cert@gitlab/app-52161/kv/cert/qa@estimatesbre_cert
      TF_VAR_brokerxl_cert@gitlab/app-52161/kv/cert/qa@brokerxl_cert
      TF_VAR_broker_cert@gitlab/app-52161/kv/cert/qa@broker_cert
      TF_VAR_guidance_cert@gitlab/app-52161/kv/cert/qa@guidance_cert
      TF_VAR_collection_cert@gitlab/app-52161/kv/cert/qa@collection_cert
      TF_VAR_actualsbre_cert@gitlab/app-52161/kv/cert/qa@actualsbre_cert
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.74
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v4.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "application-gateway"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

######################
### automation account ####
######################
deploy-qa-automation-account-1:
  extends: [.iac_qa_deploy_template]
  variables:
    CLUSTER: "${ENV}_automationaccount_1"
    TERRAFORM_PATH: "${BAS_CICD_PROJECT_DIR}/terraform/automationaccount"
    TERRAFORM_VAR_FILE: "${BAS_CICD_PROJECT_DIR}/environments/${ENV}/terraform-vars/${CLUSTER}.tfvars"
    TF_CORE_TERRAFORM_PLAN_ARGS: "-var-file=${TERRAFORM_VAR_FILE}"
    TERRAFORM_STATE_FILE: "tfstate/${CI_PROJECT_NAME}/${CLUSTER}.tfstate"
    TF_CORE_TERRAFORM_APPLY_ARGS: "-var-file=${TERRAFORM_VAR_FILE} -parallelism=1"
  trigger:
    include:
      - project: 'app/itc-93303/bas-cicd-templates'
        ref: templates-0.0.29
        file: 'templates/iac/pipelines/bas-azure-iac-tfcore-developer-pipeline-v3.yaml'
        inputs:
          env: "qa"
          rgn: "eus2"
          svc: "automation-account"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

